### ISSUE TITLE
Could not compile toml_edit due to recursion limit reached

### ISSUE THREAD

**Issue by bupknar** [ordian/toml_edit#51] opened 2018-06-30 13:01 UTC
I am trying to install `cargo-edit`, which fails on trying to compile `toml_edit`.  Building `toml_edit` by itself also fails.  Minimal test case:

```
bram@raggel:~/Code$ cargo new --bin toml_edit_test
     Created binary (application) `toml_edit_test` project
bram@raggel:~/Code$ cd toml_edit_test/
bram@raggel:~/Code/toml_edit_test$ vi Cargo.toml 
bram@raggel:~/Code/toml_edit_test$ cat Cargo.toml 
[package]
name = "toml_edit_test"
version = "0.1.0"
authors = ["..."]

[dependencies]
toml_edit = "*"
bram@raggel:~/Code/toml_edit_test$ cargo build -vv
[...]
   Compiling toml_edit v0.1.2
     Running `rustc --crate-name toml_edit /home/bram/.cargo/registry/src/github.com-1ecc6299db9ec823/toml_edit-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' -C metadata=33d17469c5ea603f -C extra-filename=-33d17469c5ea603f --out-dir /home/bram/Code/toml_edit_test/target/debug/deps -L dependency=/home/bram/Code/toml_edit_test/target/debug/deps --extern combine=/home/bram/Code/toml_edit_test/target/debug/deps/libcombine-a3f87f244ed072d4.rlib --extern chrono=/home/bram/Code/toml_edit_test/target/debug/deps/libchrono-9e8cfa828b060d66.rlib --extern linked_hash_map=/home/bram/Code/toml_edit_test/target/debug/deps/liblinked_hash_map-e0125a89193b31b6.rlib --cap-lints warn`
error: reached the recursion limit while instantiating `<parser::datetime::date_time<combine::easy::Stream<combine::stream::state::State<&str, combine::stream::state::SourcePosition>>> as combine::Parser>::parse_mode::<combine::parser::FirstMode>`

error: aborting due to previous error

error: Could not compile `toml_edit`.

Caused by:
  process didn't exit successfully: `rustc --crate-name toml_edit /home/bram/.cargo/registry/src/github.com-1ecc6299db9ec823/toml_edit-0.1.2/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" -C metadata=33d17469c5ea603f -C extra-filename=-33d17469c5ea603f --out-dir /home/bram/Code/toml_edit_test/target/debug/deps -L dependency=/home/bram/Code/toml_edit_test/target/debug/deps --extern combine=/home/bram/Code/toml_edit_test/target/debug/deps/libcombine-a3f87f244ed072d4.rlib --extern chrono=/home/bram/Code/toml_edit_test/target/debug/deps/libchrono-9e8cfa828b060d66.rlib --extern linked_hash_map=/home/bram/Code/toml_edit_test/target/debug/deps/liblinked_hash_map-e0125a89193b31b6.rlib --cap-lints warn` (exit code: 101)
bram@raggel:~/Code/toml_edit_test$ rustc -V
rustc 1.27.0 (3eda71b00 2018-06-19)
```

I am using Linux x86_64, on a pretty low-specced netbook (2 cores, 4GB RAM).  I am curious as to why this fails to compile, as I have installed `cargo-edit` (and thus `toml_edit`) on a couple of x86_64 machines using the same `rustc` version over the last couple of days, which all worked fine.  Is `rustc`'s recursion limit dynamic based on the machine's specs?  That's the only thing I can think of why compilation fails on this netbook, and not on other machines.

**Comment by ordian** [comment] 2018-06-30 13:51
Hey @bupknar!

That's an interesting issue. I don't know much about how rustc handles recursion limit, but it seems to be a fixed value (https://github.com/rust-lang/rust/blob/6c537493d01694cc6e0a614dff12c475055aa2b4/src/librustc/middle/recursion_limit.rs#L25). Do you have an x86_64 CPU as well?

Could you checkout the branch `recursion_limit`? I
```
$ git clone https://github.com/ordian/toml_edit
$ git checkout recursion_limit
$ cargo +stable build
```

**Comment by ordian** [comment] 2018-06-30 13:58
Hm, actually I can reproduce the issue on my not-so-low-specced laptop.

**Comment by ordian** [comment] 2018-06-30 14:13
Seems like a regression introduced in https://github.com/Marwes/combine. It should be fixed there https://github.com/Marwes/combine/issues/172.

**Closed** 2018-06-30 20:56 UTC
Labels: bug, dependencies

**Comment by bupknar** [comment] 2018-07-01 13:40
Thank you so much for the very quick investigation and fix, @ordian! :smile:
